# Generated by Django 5.2.7 on 2025-12-13 05:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=4)),
                ('nome', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Companhia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Aeroporto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=4)),
                ('nome', models.CharField(max_length=64)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_api', models.UUIDField()),
                ('codigo', models.CharField(max_length=8)),
                ('ativo', models.BooleanField(default=True)),
                ('companhia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.companhia')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aeroporto_destino', to='api.aeroporto')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aeroporto_origem', to='api.aeroporto')),
            ],
        ),
        migrations.CreateModel(
            name='StatusVoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('EMBARCANDO', 'Embarcando'), ('ULTIMA_CHAMADA', 'Última chamada'), ('DECOLADO', 'Decolado'), ('APROXIMANDO', 'Aproximando'), ('POUSADO', 'Pousado'), ('DESEMBARCANDO', 'Desembarcando'), ('FINALIZADO', 'Finalizado')], max_length=16)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('voo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.voo')),
            ],
        ),
        migrations.CreateModel(
            name='PosicaoVoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.CharField(choices=[('ORIGEM', 'Origem'), ('EM_VOO', 'Em voo'), ('DESTINO', 'Destino')], max_length=16)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('voo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.voo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalheHorarioVoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previsao_decolagem', models.DateTimeField()),
                ('horario_decolagem', models.DateTimeField(null=True)),
                ('previsao_pouso', models.DateTimeField(null=True)),
                ('horario_pouso', models.DateTimeField(null=True)),
                ('voo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.voo')),
            ],
        ),
    ]
