# Generated by Django 5.2.7 on 2025-10-23 21:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=4)),
                ('nome', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Aeroporto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=8)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=8)),
                ('status', models.CharField(choices=[], max_length=8)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aeroporto_destino', to='api.aeroporto')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aeroporto_origem', to='api.aeroporto')),
            ],
        ),
    ]
