# Generated by Django 5.2.7 on 2025-10-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusvoo',
            name='posicao',
            field=models.CharField(choices=[('ORIGEM', 'Origem'), ('EM_VOO', 'Em voo'), ('DESTINO', 'Destino')], max_length=16),
        ),
        migrations.AlterField(
            model_name='statusvoo',
            name='status',
            field=models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('DECOLADO', 'Decolado'), ('CANCELADO', 'Cancelado'), ('ULTIMA_CHAMADA', 'Última chamada'), ('ENCERRADO', 'Encerrado')], max_length=16),
        ),
    ]
