# Generated by Django 5.2.7 on 2025-11-16 01:45
from django.core.management import call_command
from django.db import migrations

def load_data_cidades(apps, schema_editor):
    call_command('loaddata', 'api/fixture/cidades.json', app_label='api', verbosity=0)

def load_data_aeroportos(apps, schema_editor):
    call_command('loaddata', 'api/fixture/aeroportos.json', app_label='api', verbosity=0)

def load_data_compahias(apps, schema_editor):
    call_command('loaddata', 'api/fixture/companhias.json', app_label='api', verbosity=0)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data_cidades),
        migrations.RunPython(load_data_aeroportos),
        migrations.RunPython(load_data_compahias),
    ]
