# Generated by Django 5.2.7 on 2025-11-16 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20251116_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusvoo',
            name='portao',
        ),
        migrations.RemoveField(
            model_name='statusvoo',
            name='status',
        ),
    ]
